In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv(r"C:\Users\P15\Desktop\sale_data_analysis_pipeline\data\customers.csv")
orders = pd.read_csv(r"C:\Users\P15\Desktop\sale_data_analysis_pipeline\data\orders.csv")
products = pd.read_csv(r"C:\Users\P15\Desktop\sale_data_analysis_pipeline\data\products.csv")

### Customers Data Exploration

In [3]:
customers.head()

   customer_id              name  country
0            1      George Davis      USA
1            2    Hannah Jackson  Germany
2            3  Thomas Rodriguez    India
3            4        Chris Hall    India
4            5        Sam Garcia    Japan

In [6]:
customers.describe(include='all')

        customer_id              name country
count    250.000000               250     250
unique          NaN               237      15
top             NaN  Thomas Rodriguez   Italy
freq            NaN                 2      22
mean     125.500000               NaN     NaN
std       72.312977               NaN     NaN
min        1.000000               NaN     NaN
25%       63.250000               NaN     NaN
50%      125.500000               NaN     NaN
75%      187.750000               NaN     NaN
max      250.000000               NaN     NaN

In [7]:
customers.shape

(250, 3)

In [8]:
customers.dtypes

customer_id    int64
name             str
country          str
dtype: object

In [9]:
customers.isnull().sum()

customer_id    0
name           0
country        0
dtype: int64

In [27]:
customers.duplicated().sum()

np.int64(0)

In [12]:
customers['country'].value_counts()

country
Italy          22
Sweden         22
Germany        21
Brazil         20
Mexico         20
USA            17
Japan          16
Spain          16
Netherlands    15
France         15
India          14
Australia      14
Morocco        13
UK             13
Canada         12
Name: count, dtype: int64

In [14]:
customers.memory_usage(deep=True) / 1024 ** 2

Index          0.000126
customer_id    0.001907
name           0.004705
country        0.003319
dtype: float64

### Orders Data Exporation

In [15]:
orders.head()

   order_id  customer_id  product_id  quantity  order_date
0         1          242          70         5  2024-10-03
1         2          127         113         1  2024-11-02
2         3           11         111         3  2024-11-05
3         4           65           7         1  2024-04-27
4         5          247         173         5  2024-10-27

In [16]:
orders.tail()

     order_id  customer_id  product_id  quantity  order_date
495       496          194         138         4  2024-05-03
496       497          218          58         3  2024-12-28
497       498           37         207         4  2024-01-30
498       499          144         106         4  2024-10-12
499       500          136          35         4  2024-05-04

In [17]:
orders.dtypes

order_id       int64
customer_id    int64
product_id     int64
quantity       int64
order_date       str
dtype: object

In [18]:
orders.shape

(500, 5)

In [19]:
orders.isnull().sum()

order_id       0
customer_id    0
product_id     0
quantity       0
order_date     0
dtype: int64

In [20]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     500 non-null    int64
 1   customer_id  500 non-null    int64
 2   product_id   500 non-null    int64
 3   quantity     500 non-null    int64
 4   order_date   500 non-null    str
dtypes: int64(4), str(1)
memory usage: 24.5 KB

In [21]:
orders.describe()

         order_id  customer_id  product_id    quantity
count  500.000000   500.000000   500.00000  500.000000
mean   250.500000   122.860000   110.86400    3.110000
std    144.481833    68.591121    63.11682    1.374656
min      1.000000     3.000000     1.00000    1.000000
25%    125.750000    66.000000    58.00000    2.000000
50%    250.500000   120.500000   107.50000    3.000000
75%    375.250000   174.000000   167.25000    4.000000
max    500.000000   250.000000   216.00000    5.000000

### Products Data Exploration

In [22]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    216 non-null    int64
 1   product_name  216 non-null    str
 2   category      216 non-null    str
 3   price         216 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 10.6 KB

In [23]:
products.describe(include="all")

        product_id product_name category        price
count      216.000          216      216   216.000000
unique         NaN          216        7          NaN
top            NaN   Smartphone    Books          NaN
freq           NaN            1       34          NaN
mean       108.500          NaN      NaN   198.557870
std         62.498          NaN      NaN   292.786078
min          1.000          NaN      NaN     5.360000
25%         54.750          NaN      NaN    31.487500
50%        108.500          NaN      NaN    80.330000
75%        162.250          NaN      NaN   209.037500
max        216.000          NaN      NaN  1421.790000

In [24]:
products.isnull().sum()

product_id      0
product_name    0
category        0
price           0
dtype: int64

In [25]:
products['category'].value_counts()

category
Books          34
Clothing       33
Home           31
Electronics    30
Sports         30
Toys           30
Beauty         28
Name: count, dtype: int64

In [26]:
products.duplicated().sum()

np.int64(0)

### Data Cleaning & Preprocessing [Customers]

In [28]:
customers.dropna(inplace=True)

In [29]:
customers['country'] = customers['country'].str.lower().str.strip()

In [30]:
customers['name'] = customers['name'].str.strip().str.lower()

In [31]:
customers['customer_id'] = customers['customer_id'].astype('int16')

In [32]:
customers.columns

Index(['customer_id', 'name', 'country'], dtype='str')

In [61]:
customers.dtypes

customer_id            int16
customer_name            str
customer_country    category
dtype: object

In [60]:
customers['customer_country'] = customers['customer_country'].astype('category')

In [36]:
customers.rename(columns={
    "customer_id":"customer_id",
    "name":"customer_name",
    "country":"customer_country"
}, inplace=True)

In [37]:
customers.columns

Index(['customer_id', 'customer_name', 'customer_country'], dtype='str')

### Data Cleaning & Preprocessing [Products]

In [ ]:
products.dropna(inplace=True)

In [40]:
products.columns

Index(['product_id', 'product_name', 'category', 'price'], dtype='str')

In [44]:
products.rename(columns={
    "category":"product_category",
    "price_category":"product_price"
}, inplace=True)

In [45]:
products.dtypes

product_id            int64
product_name            str
product_category        str
product_price       float64
dtype: object

In [46]:
products['product_name'] = products['product_name'].str.strip().str.lower()

In [47]:
products['product_category'] = products['product_category'].str.strip().str.lower()

In [50]:
products.head()

   product_id     product_name product_category  product_price
0           1       smartphone      electronics         702.60
1           2   smartphone_pro      electronics        1140.08
2           3  smartphone_plus      electronics        1267.80
3           4           laptop      electronics        1160.43
4           5       laptop_pro      electronics         805.88

In [56]:
products['product_category'] = products['product_category'].astype("category")

In [58]:
products.dtypes

product_id             int64
product_name             str
product_category    category
product_price        float64
dtype: object

In [49]:
products["product_name"] = products["product_name"].str.replace(" ","_")

### Data Cleaning & Preprocessing [Orders]

In [51]:
orders.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'order_date'], dtype='str')

In [52]:
orders['order_date'] = pd.to_datetime(orders['order_date'], utc=True)

In [53]:
orders.head()

   order_id  customer_id  product_id  quantity                order_date
0         1          242          70         5 2024-10-03 00:00:00+00:00
1         2          127         113         1 2024-11-02 00:00:00+00:00
2         3           11         111         3 2024-11-05 00:00:00+00:00
3         4           65           7         1 2024-04-27 00:00:00+00:00
4         5          247         173         5 2024-10-27 00:00:00+00:00

In [54]:
orders.dtypes

order_id                     int64
customer_id                  int64
product_id                   int64
quantity                     int64
order_date     datetime64[us, UTC]
dtype: object

In [55]:
orders.dropna(inplace=True)

### Let's merge tables

In [62]:
print(orders.columns)
print(customers.columns)
print(products.columns)

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'order_date'], dtype='str')
Index(['customer_id', 'customer_name', 'customer_country'], dtype='str')
Index(['product_id', 'product_name', 'product_category', 'product_price'], dtype='str')

In [64]:
df1 = orders.merge(customers, on="customer_id", how="left")

In [66]:
df1.head()

,order_id,customer_id,product_id,quantity,order_date,customer_name,customer_country
0,1,242,70,5,2024-10-03 00:00:00+00:00,owen wright,morocco
1,2,127,113,1,2024-11-02 00:00:00+00:00,sarah carter,spain
2,3,11,111,3,2024-11-05 00:00:00+00:00,adam thomas,morocco
3,4,65,7,1,2024-04-27 00:00:00+00:00,leo mitchell,france
4,5,247,173,5,2024-10-27 00:00:00+00:00,max robinson,japan

In [68]:
df2 = orders.merge(products, on='product_id',how="left")
df2.head()

,order_id,customer_id,product_id,quantity,order_date,product_name,product_category,product_price
0,1,242,70,5,2024-10-03 00:00:00+00:00,jacket_plus,clothing,114.71
1,2,127,113,1,2024-11-02 00:00:00+00:00,comic_book_pro,books,16.77
2,3,11,111,3,2024-11-05 00:00:00+00:00,history_book_plus,books,21.26
3,4,65,7,1,2024-04-27 00:00:00+00:00,headphones,electronics,687.82
4,5,247,173,5,2024-10-27 00:00:00+00:00,hair_dryer_pro,beauty,58.47

In [73]:
df = orders.merge(customers, on="customer_id", how="left").merge(products, on="product_id", how="left")
df.head()

,order_id,customer_id,product_id,quantity,order_date,customer_name,customer_country,product_name,product_category,product_price
0,1,242,70,5,2024-10-03 00:00:00+00:00,owen wright,morocco,jacket_plus,clothing,114.71
1,2,127,113,1,2024-11-02 00:00:00+00:00,sarah carter,spain,comic_book_pro,books,16.77
2,3,11,111,3,2024-11-05 00:00:00+00:00,adam thomas,morocco,history_book_plus,books,21.26
3,4,65,7,1,2024-04-27 00:00:00+00:00,leo mitchell,france,headphones,electronics,687.82
4,5,247,173,5,2024-10-27 00:00:00+00:00,max robinson,japan,hair_dryer_pro,beauty,58.47